### ISSUE TITLE
add highlight feature in disassembly text view. just like, graph view.

### ISSUE THREAD

**Issue by HarshilPatel007** [rizinorg/cutter#2692] opened 2021-05-16 07:58 UTC
**version info**
- Cutter-v2.0.2-x64.Linux.AppImage
- Downloaded from website.
- OS : I Use Arch BTW :laughing: :stuck_out_tongue:

**Is your feature request related to a problem? Please describe.**
yes, when we highlight instruction(s) in disassembly graph view, it doesn't appear in text view.
also highlight option in text view doesn't exist. it only available in graph view.

**Describe the solution you'd like**
enable highlight option in disassembly text view as well and make it sync with graph view obviously.
[disassembly graph view highlights instruction]
![Screenshot from 2021-05-16 13-11-42](https://user-images.githubusercontent.com/16424866/118389821-64815f00-b649-11eb-98ff-57d53c5a9854.png)
[disassembly text view highlights instruction doesn't showing/appearing]
![Screenshot from 2021-05-16 13-20-48](https://user-images.githubusercontent.com/16424866/118389842-8c70c280-b649-11eb-8ebb-c06392e8b680.png)

**Comment by ITAYC0HEN** [comment] 2021-05-17 07:47
I think it is a duplicate of #444 which has some discussions in it.
I think that your suggestion for syncing the highlights from graph to disassembly and vice versa wasn't mentioned and it is a good idea :)

I will close this issue as a "duplicate" now, please add your notes and feedback in #444 because you have some very nice suggestions 👍 🎉

**Closed by ITAYC0HEN** 2021-05-17 07:47 UTC
