### ISSUE TITLE
Reference and display are out of sync

### ISSUE THREAD

**Issue by crackcm** [rizinorg/cutter#2712] opened 2021-07-01 03:20 UTC
**Environment information**
* Operating System:
* Cutter version:
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by crackcm** [comment] 2021-07-01 03:20
Reference and display are out of sync

**Comment by xarkes** [comment] 2021-07-01 07:14
Hello,
Could you be more specific about this issue please?
With no context it's really hard for me to understand what the problem is.
If you can give steps on how to reproduce it would be helpful :)
Thanks.

**Comment by crackcm** [comment] 2021-07-01 08:11
shift + x Reference  variable Display error

**Comment by crackcm** [comment] 2021-07-01 08:12
Sorry, the picture cannot be uploaded

**Comment by XVilka** [comment] 2023-02-03 13:05
I am closing this as the description is unclear. Please open a new issue if you think it's necessary, but with more details.

**Closed by XVilka** 2023-02-03 13:05 UTC
