### ISSUE TITLE
Can't load Ghidra decompiler on Windows 10

### ISSUE THREAD

**Issue by Grivus** [rizinorg/cutter#2684] opened 2021-04-25 15:05 UTC
**Environment information**
* Operating System: Windows 10 1909
* Cutter version: 2.0.1
* Obtained from:
  - Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - Distribution repository

**Describe the bug**
During cutter start there are several error messages I have:

1. First error pops up about "The Rizin standard themes could not be found in 'D:/a/cutter/cutter/build//share/cons' Most likely, Rizin is not properly installed." However, I would say, that such a path on Windows seems to be illegal, and there is no installation at all - just extracting from archive. 
2. Next two errors I got during regarding plugins: 
`Plugins are loaded from "D:/Programs/cutter-v2.0.1-x64.Windows/plugins"
Load Error for plugin "rz_ghidra_cutter.dll" : "Cannot load library D:\\Programs\\cutter-v2.0.1-x64.Windows\\plugins\\native\\rz_ghidra_cutter.dll: РќРµ РЅР°Р№РґРµРЅ СѓРєР°Р·Р°РЅРЅС‹Р№ РјРѕРґСѓР»СЊ."
Load Error for plugin "rz_ghidra_cutter.lib" : "Failed to extract plugin meta data from 'D:/Programs/cutter-v2.0.1-x64.Windows/plugins/native/rz_ghidra_cutter.lib'"`

After all that Cutter starts, but the decompiler is Empty all the time.

**To Reproduce**

Just download latest build (2.0.1) from github releases, extract and try to launch Cutter.exe

**Expected behavior**

No error about color theme; all plugins loaded correctly. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1619477/115998472-0d5f1000-a5f0-11eb-957e-ad97da8e6fa6.png)
![image](https://user-images.githubusercontent.com/1619477/115998484-22d43a00-a5f0-11eb-8c29-46fe8911e951.png)

**Additional context**

There are no unicode paths with complicated symbols I can see; 
Also there is a cutter.ini file in users roaming rizin directory with the content I would say seems like color themes.

**Comment by karliss** [comment] 2021-04-25 15:11
Duplicate of #2667 . Bugfix release is planned today.

**Closed by karliss** 2021-04-25 15:11 UTC
