### ISSUE TITLE
KSyntaxHighlighting is now available on Qt6

### ISSUE THREAD

**Issue by david-geiger** [rizinorg/cutter#3333] opened 2024-04-21 19:26 UTC
Can KSyntaxHighlighting support be re-enable for CUTTER_QT6 as it is now available since KF6, please?

**Comment by XVilka** [comment] 2024-04-21 23:21
Duplicate of https://github.com/rizinorg/cutter/issues/3221

**Closed as completed by XVilka** 2024-04-21 23:21 UTC
