### ISSUE TITLE
Release source file should include translation scripts

### ISSUE THREAD

**Issue by dmknght** [rizinorg/cutter#3013] opened 2022-08-10 19:35 UTC
**Is your feature request related to a problem? Please describe.**

Current Cuter is having translation scripts as sub modules. In release tarball (ver 2.1.0), those files are missing
![image](https://user-images.githubusercontent.com/29118926/184004449-2cd732ab-7f17-4449-8ae2-2fdcadf07550.png)

When i tried build type `Release`, it failed to use Cmake automation installation
```
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
CMake Error at src/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/tmp/rizin-cutter/obj-x86_64-linux-gnu/src/translations/cutter_ar.qm": No
  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)
```

**Describe the solution you'd like**

New Release / Tag should have translation scripts

**Comment by karliss** [comment] 2022-08-10 20:16
Duplicate of https://github.com/rizinorg/cutter/issues/2878

For now I don't recommend Cutter source tarballs. They are currently not created with intention to be used by package mainters. They are there just because Github creates them automatically (not sure if there is even an easy way to disable them). (currently) they should not be consider an indicator for when the release is officially released. When the tag is there and the new entry in github release made public consider the release officially out. 

For now better clone the corresponding git tag. You have access not only to release source but also all the other commits. This not the project where only developers get access to source control and everyone else gets source tarball once a year in a CD. 

This doesn't mean that this will never be done. We could and probably should create proper tarballs to make it more friendly for distros that have the packaging workflow made purely around source archives ignoring the last 10 years of changes in availability of technological means for distributing source code.

**Closed as not planned by karliss** 2022-08-10 20:16 UTC
Labels: Duplicate
