### ISSUE TITLE
cutter could not be open on may macos 10.15.6

### ISSUE THREAD

**Issue by smartether** [rizinorg/cutter#2447] opened 2020-10-15 16:08 UTC
**Environment information**
* Operating System: macos
* Cutter version: 1.12.0
* Obtained from:
  - [] Built from source
  - [x ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

cutter could not be open on may macos 10.15.6
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ITAYC0HEN** [comment] 2020-10-15 17:54
Hi, thank you for opening an issue :)
Seems like you didn't fill the issue template and thus, your issue is lacking important information we need to know.
Please fill the issue with all the detailed and relevant information so we will be able to fully help you.
Attach files, screenshots and reproducers if you can.

Thanks!

**Comment by doomguy** [comment] 2020-10-23 06:57
Gotta chime in since i got the same issue here:

**Environment information**
* Operating System: macOS 10.15.7
* Cutter version: 1.12.0
* Obtained from:
  * [ ] Built from source
  * [x] Downloaded release from Cutter website or GitHub
  * [ ] Distribution repository
* File format:

 % shasum -a 256 Cutter-v1.12.0-x64.macOS.dmg 
700327f904de00a29b8622eb7548b96181c50f0842d726a84be2a8f7558cae83  Cutter-v1.12.0-x64.macOS.dmg

**Describe the bug**
I you try to run cutter by just running the .app, nothing happens.

From command line it looks like the following:
```
doomguy@phobos /Applications % ./Cutter.app/Contents/MacOS/Cutter    
Cutter Launch Script for macOS 🥞
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Applications/Cutter.app/Contents/Frameworks/Python.framework/Versions/3.6/Python
  Reason: image not found
./Cutter.app/Contents/MacOS/Cutter: line 8: 93956 Abort trap: 6           "$EXECDIR/Cutter.bin" "$@"
```

**Expected behavior**
Cutter starts up.

**Additional context**
StackOverlow has similar issues for other projects: 
* https://stackoverflow.com/questions/15860543/dyld-library-not-loaded-usr-local-libodep-lib-libintl-8-dylib

My system has no "heavy customization" like brew or macports installed. Seems like cutter needs to be shipped with an additional library `libintl.8.dylib` to work out of the box.

**Comment by doomguy** [comment] 2020-10-23 07:02
This tickets seems to be a dupe of #2428.

**Comment by robinelvin** [comment] 2020-11-09 14:26
Same error here:

```
rob@Mac-mini alto % /Applications/Cutter.app/Contents/MacOS/Cutter
Cutter Launch Script for macOS 🥞
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Applications/Cutter.app/Contents/Frameworks/Python.framework/Versions/3.6/Python
  Reason: image not found
/Applications/Cutter.app/Contents/MacOS/Cutter: line 8: 29400 Abort trap: 6           "$EXECDIR/Cutter.bin" "$@"
```

I think this may be a different issue to the one documented in #2428

**Comment by xarkes** [comment] 2021-02-13 07:38
I'm taking the liberty to close this issue as the other macOS one was fixed. This behavior should be present in the next release of Cutter.
Feel free to reopen if necessary.

**Closed by xarkes** 2021-02-13 07:38 UTC
Labels: macOS
