### ISSUE TITLE
Mac OS Crash in Cutter

### ISSUE THREAD

**Issue by Maijin** [rizinorg/cutter#1957] opened 2019-12-21 10:15 UTC
**Environment information**
* Operating System: Mac OS
* Cutter version: 1.10
* File format: PE

**Describe the bug**

Cutter crashed see crashdump

**To Reproduce**

User opened the PE and it eventually crashed.

**Expected behavior**

Cutter doesn't crash

[Cutter_crash_dump_21.12.19_10.32.37.dmp.zip](https://github.com/radareorg/cutter/files/3991276/Cutter_crash_dump_21.12.19_10.32.37.dmp.zip)

From @Th4nat0s

**Comment by XVilka** [comment] 2021-09-26 04:46
Need to check first if this still happens.

**Comment by Th4nat0s** [comment] 2021-09-27 18:29
Can't reproduce, run with Version 2.0.3

**Comment by xarkes** [comment] 2021-09-28 07:24
Thanks for the feedback, marking as solved :)

**Closed** 2021-09-28 07:27 UTC
Labels: BUG, macOS, High Priority
