### ISSUE TITLE
Cutter build is broken in docker after second run

### ISSUE THREAD

**Issue by Misiur** [rizinorg/cutter#2140] opened 2020-04-11 15:39 UTC
Win 10 x64
```
[root@LAPTOP-EJ5BH6DJ docker]:~/dev/private/re/cutter/docker (v13.11.0) (master) make LOCAL_DEV=y build
sudo docker build --rm -t radareorg/cutter -f ./Dockerfile-dev ../
Sending build context to Docker daemon  49.88MB
Step 1/23 : FROM alpine:latest AS builder
 ---> a187dde48cd2
Step 2/23 : LABEL maintainer "Philipp Schmied <ps1337@mailbox.org>"
 ---> Using cache
 ---> ff57996e4ffc
Step 3/23 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> f94a050a5379
Step 4/23 : RUN apk add --no-cache         bash         cmake         curl         g++         gcc         git         linux-headers         make         pkgconfig         python3-dev         qt5-qtbase         qt5-qtsvg-dev         qt5-qttools-dev         unzip         wget
 ---> Using cache
 ---> 74f4a2d383c2
Step 5/23 : COPY docker/build_radare2.sh /opt/cutter/
 ---> Using cache
 ---> 891515824ac3
Step 6/23 : COPY radare2 /opt/cutter/radare2
 ---> Using cache
 ---> 0a73295e66e3
Step 7/23 : WORKDIR /opt/cutter
 ---> Using cache
 ---> bc6f07f4eea3
Step 8/23 : RUN bash build_radare2.sh
 ---> Using cache
 ---> 030f0cc0ac00
Step 9/23 : COPY docker/build_cutter.sh /opt/cutter/
 ---> Using cache
 ---> 0cf0a912eefd
Step 10/23 : COPY scripts /opt/cutter/scripts
 ---> Using cache
 ---> 0819d9a7e647
Step 11/23 : COPY src /opt/cutter/src
 ---> Using cache
 ---> 3fa6f930843d
Step 12/23 : RUN bash build_cutter.sh &&     bash -c 'if [[ ! -x "/opt/cutter/build/Cutter" ]]; then exit -1; fi'
 ---> Using cache
 ---> e9caad7cffac
Step 13/23 : FROM alpine:latest AS runner
 ---> a187dde48cd2
Step 14/23 : ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
 ---> Using cache
 ---> cd8baec9c32e
Step 15/23 : RUN apk add --no-cache         bash         libuuid         make         python3         qt5-qtbase         shadow         su-exec
 ---> Using cache
 ---> fa81ceb72c40
Step 16/23 : RUN useradd r2
 ---> Using cache
 ---> 054e05960406
Step 17/23 : RUN mkdir /var/sharedFolder &&     mkdir -p /home/r2/.config/radare2 &&     touch /home/r2/.radare2rc &&     chown -R r2:r2 /var/sharedFolder &&     chown -R r2:r2 /home/r2/
 ---> Using cache
 ---> 83e6d9dc9413
Step 18/23 : COPY ./docker/entrypoint.sh /usr/local/bin/entrypoint.sh
 ---> Using cache
 ---> 23ea9656d7ad
Step 19/23 : COPY --from=builder /opt/cutter /opt/cutter
 ---> Using cache
 ---> 0b5dd6f9c639
Step 20/23 : COPY --from=builder /usr/lib /usr/lib
 ---> Using cache
 ---> f2a4b3ad2ab9
Step 21/23 : COPY --from=builder /usr/share/radare2 /usr/share/radare2
 ---> Using cache
 ---> 526f34c71656
Step 22/23 : WORKDIR /opt/cutter/radare2/binr
 ---> Using cache
 ---> 97123760136a
Step 23/23 : RUN make install && make symstall install-symlink
 ---> Using cache
 ---> 1578b0b6646d
Successfully built 1578b0b6646d
Successfully tagged radareorg/cutter:latest
[root@LAPTOP-EJ5BH6DJ docker]:~/dev/private/re/cutter/docker (v13.11.0) (master) docker run --rm -it radareorg/cutter
Cutter: Starting with UID:GID :
usermod: invalid user ID 'r2'
Usage: usermod [options] LOGIN

Options:
  -c, --comment COMMENT         new value of the GECOS field
  -d, --home HOME_DIR           new home directory for the user account
  -e, --expiredate EXPIRE_DATE  set account expiration date to EXPIRE_DATE
  -f, --inactive INACTIVE       set password inactive after expiration
                                to INACTIVE
  -g, --gid GROUP               force use GROUP as new primary group
  -G, --groups GROUPS           new list of supplementary GROUPS
  -a, --append                  append the user to the supplemental GROUPS
                                mentioned by the -G option without removing
                                the user from other groups
  -h, --help                    display this help message and exit
  -l, --login NEW_LOGIN         new value of the login name
  -L, --lock                    lock the user account
  -m, --move-home               move contents of the home directory to the
                                new location (use only with -d)
  -o, --non-unique              allow using duplicate (non-unique) UID
  -p, --password PASSWORD       use encrypted password for the new password
  -R, --root CHROOT_DIR         directory to chroot into
  -P, --prefix PREFIX_DIR       prefix directory where are located the /etc/* files
  -s, --shell SHELL             new login shell for the user account
  -u, --uid UID                 new UID for the user account
  -U, --unlock                  unlock the user account
  -v, --add-subuids FIRST-LAST  add range of subordinate uids
  -V, --del-subuids FIRST-LAST  remove range of subordinate uids
  -w, --add-subgids FIRST-LAST  add range of subordinate gids
  -W, --del-subgids FIRST-LAST  remove range of subordinate gids

qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

[root@LAPTOP-EJ5BH6DJ docker]:~/dev/private/re/cutter/docker (v13.11.0) (master) 
```

**Comment by ITAYC0HEN** [comment] 2020-04-11 15:41
cc @ps1337

**Comment by karliss** [comment] 2020-04-11 15:51
@Misiur I don't see any problems in the log you attached. Build finishes and cutter fails to open because you don't have any displays available within docker which seems reasonable.

**Comment by Misiur** [comment] 2020-04-11 15:59
It worked correctly the first time I run it

**Comment by karliss** [comment] 2020-04-11 16:20
What do you mean by worked, did it somehow opened the GUI? Can you demonstrate a full log that demonstrates working the first time and then failing on second time? Or did it worked once and you can't repeat that at all?

**Comment by ps1337** [comment] 2020-04-11 16:36
I'll check it out later and provide feedback 



-----Original Message-----

**Comment by ps1337** [comment] 2020-04-11 16:55
The image build is fine. We usually start the docker container using the Makefile that's present here: https://github.com/radareorg/cutter/blob/master/docker/Makefile

The problem is that the container expects some environment variables to be present in order to change the internal container user from `root` to `r2`. Also, the X socket is mounted inside of the container so the GUI can be shown.

Please retry by using our Makefile, e.g. like `sudo make run`

**Comment by XVilka** [comment] 2023-02-03 13:34
A lot has changed since in the code and building process. Closing this. Feel free to open a new issue if there are still any problems with building Cutter.

**Closed by XVilka** 2023-02-03 13:34 UTC
