### ISSUE TITLE
Rz-diff feature in Cutter

### ISSUE THREAD

**Issue by GermanAizek** [rizinorg/cutter#3284] opened 2024-01-20 14:08 UTC
Is it possible to use rz-diff in GUI cutter? Select both binary and diff him graph overview. I understand that I can open two different Cutter windows context, but then how i can compare similarity functions?

**Comment by XVilka** [comment] 2024-01-20 15:33
A duplicate of https://github.com/rizinorg/cutter/issues/1104

There is some work going on this feature, but it's not yet merged. It's hindered mainly by the lack of thread safety in Rizin because of the many globals/statics still being presented. We have already removed most and continuing to remove more, but it's not yet complete: https://github.com/rizinorg/rizin/issues/4055

**Closed as completed by XVilka** 2024-01-20 15:33 UTC
