### ISSUE TITLE
Crash in about 30 seconds during the analysis phase

### ISSUE THREAD

**Issue by fenginsc** [rizinorg/cutter#2694] opened 2021-05-25 12:30 UTC
[**Environment](url) information**
* Operating System:windows7 x64
* Cutter version:2.0.2
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:
     windows pe x86 file
     https://download.sublimetext.com/Sublime%20Text%20Build%203211%20Setup.exe
     sublime_text.exe
**Describe the bug**
     Crash in about 30 seconds during the analysis phase.
     But using cutter 1.10 version does not have this problem.

**To Reproduce**

It will crash during the analysis phase and cannot be started.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tvcat** [comment] 2021-06-16 14:08
OS: Windows 10 Pro x64
Cutter: 2.0.2

Having the same problem when analyse termsrv.dll version 21966.1 x64
Open without crash with Cutter version 1.12
Let me know if you need more information.

**Comment by xarkes** [comment] 2021-06-16 19:00
Just tested on Linux with master, I could not reproduce the crash.
Probably it is something Windows specific.

**Comment by Tanishq-Banyal** [comment] 2021-07-16 05:24
same issue, here is a crash dump :-

[Cutter_crash_dump_16.07.21_09.36.50.zip](https://github.com/rizinorg/cutter/files/6828030/Cutter_crash_dump_16.07.21_09.36.50.zip)

Seems to me, its a Segmentation Fault.

**Comment by XVilka** [comment] 2021-09-18 09:48
I tried to reproduce with the Cutter from git, it doesn't happen anymore. cc @xarkes @thestr4ng3r

**Comment by xarkes** [comment] 2021-09-18 10:32
Just tried as well, marking as fixed.

**Closed by xarkes** 2021-09-18 10:32 UTC
Labels: BUG
