### ISSUE TITLE
Have a search bar widget, which contains results from context menu.

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#2557] opened 2021-01-06 03:04 UTC
As there are no freely assignable shortcuts so far, I often have to wander through the conext menu which sometimes turns out to get quite tiring. Sometimes I need to change a setting but don't know where in the settings to find it.

I'd be nice to have **a search bar widget, wich allows to search the context menu and other options**.
It could be activated by a simple key stroke combo, just as in jetbrain-tools like intelliJ (`[shift][shift]`).

**Comment by karliss** [comment] 2021-01-06 08:00
@Semnodime Please try to stick to the issue template.

**Comment by ITAYC0HEN** [comment] 2021-01-06 10:18
Thank you for the issue 👍 
@Semnodime, are you referring to a Command Palette? I wish to have this option as well, it very very useful.
If it is what you meant, then I believe that this issue is a duplicate of https://github.com/rizinorg/cutter/issues/1264.
Would you agree it is? If so, please close this issue and paste your comment in #1264, to enrich the conversation.

If not, please let us know what is the differences you consider, it might be an addition feature inside the Command Palette, so after all, you might find it is the same solution.

Thank you very much!

**Comment by Semnodime** [comment] 2021-01-31 05:01
Duplicate of #1264. Can be closed.

**Closed** 2021-01-31 06:32 UTC
