### ISSUE TITLE
Application becomes permanently unresponsive when trying to open project

### ISSUE THREAD

**Issue by dyc3** [rizinorg/cutter#2439] opened 2020-10-02 23:38 UTC
**Environment information**
* Operating System: Ubuntu 18.04
* Cutter version: 1.12.0
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: `.exe`, compiled from golang

**Describe the bug**

After saving my project, I am unable to reopen the project. After open is clicked, the application hangs and becomes unresponsive.

**To Reproduce**

1. Open the attached project in cutter
2. See that it never loads, and becomes unresponsive

**Expected behavior**

Expected the application to remain responsive

**Screenshots**

**Additional context**

Project is attached. [splice.zip](https://github.com/radareorg/cutter/files/5320752/splice.zip)

**Comment by ITAYC0HEN** [comment] 2020-10-03 04:09
Hi @dyc3, thank you for reporting this issue :)
Sorry for the discomfort - the Projects feature is highly unstable in radare2 and Cutter and can cause issues. We are at the last miles of having a new and working project feature and remove the old one.

There is currently nothing we can do to help with this issue.
Projects are essentially radare2 script file. In order not to lose the work, I suggest scrapping the commands that are relevant for you out of the script. Usually, it will be commands for namings (function names, flag names) and comments.

I am truly sorry for the inconvenience

**Comment by dyc3** [comment] 2020-10-03 17:46
Yeah that's my current workaround.

**Comment by lillypad** [comment] 2020-10-16 11:20
Can confirm, same issue on this end, can also be reproduced in Remnux.

```bash
sudo remnux upgrade
```

Latest version, project become unresponsive.

**Comment by dyc3** [comment] 2020-10-16 12:31
After I removed all the comments and modified `e.newshell` to be `true` in my project's `rc` file, I was able to open my project. Related to https://github.com/radareorg/radare2/issues/17776 and should be fixed when newshell is enabled be default

**Comment by Semnodime** [comment] 2020-12-21 16:48
This issue is due to `radare2` (there are multiple open bug reports regarding project loading, save files, etc.).

**Comment by Semnodime** [comment] 2020-12-21 16:51
Duplicate of https://github.com/rizinorg/cutter/issues/1971

**Comment by ITAYC0HEN** [comment] 2020-12-23 18:57
Hey! :) 
Cutter now uses the new Projects that were introduced in Rizin. The experience should be much better.

I will close this issue for now. Please open a new issue if you experience issues with the new projects.

(the Projects are not yet available in a release as we didn't release a new version. Only when building from source)

**Closed by ITAYC0HEN** 2020-12-23 18:57 UTC
Labels: Projects
