### ISSUE TITLE
The 'Strings' list is empty.

### ISSUE THREAD

**Issue by RhettVX** [rizinorg/cutter#2450] opened 2020-10-18 20:54 UTC
**Environment information**
* Operating System: windows 10
* Cutter version: 1.12.0
* File format: pe64
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
The 'Strings' panel is empty, showing 0 results.

**To Reproduce**
1. Open a binary with the default options. (aaa)
2. Click on the 'Strings' tab.
3. The panel is empty, showing 0 results.

**Expected behavior**
I expected the 'Strings' list to be populated. The dashboard shows that the binary contains strings, and sysinternals strings.exe returns them all just fine.

**Additional context**
This could be caused by the large size of the binary. (71.3 MB)

**Comment by ITAYC0HEN** [comment] 2020-11-15 20:29
Hey, thank you for opening this issue.
Can we have the binary you used? On our tests we can list the strings very nicely.
It might be an issues with handling this binary file

**Comment by karliss** [comment] 2020-11-16 09:27
In this case size might be the problem. The JSON parser used for parsing information passed from r2 to Cutter has a maximum size limit. I mentioned it as one of the problems in #2070 . In that case I was also testing with ~70 MB executable so you probably hit the same limit.

As a temporary workaround you can try these things:
* R2 has multiple options for deciding what is a string like `bin.minstr` and  `bin.maxstr` see `e??~str` to list all string related options and their descriptions. Those might help getting bellow the limit.
* If you partially know the content of string you are looking for you can also use the string mode in search widget. That way instead of r2 returning all strings (which exceeds current limitations) and cutter filtering them by search expression, r2 will only return for strings that match the query which shouldn't have problems fitting the limit.

**Comment by RhettVX** [comment] 2020-11-18 20:05
I don't believe I can publicly share the binary I'm using, but if there is a way I can share it in private I can. It probably is the size of the binary. Search does still work I believe.

**Comment by karliss** [comment] 2020-11-18 21:19
i don't think it's necessary to share it anymore since a similar problem was previously observed using freely available one.

**Comment by RhettVX** [comment] 2020-11-21 07:02
Alright, thanks.

**Comment by superewald** [comment] 2022-08-11 09:06
I have the same issue when using Cutter 2.1.0 (string list is empty but dashboard shows binary contains ~7000 strings) but it works with 2.0.5. I'm running Cutter on Linux and analyse a 24MB x86 windows PE executable.

**Comment by karliss** [comment] 2022-08-11 09:44
Assuming the cause is still the same as before it should be fixed by  #2973 . Which was not included in 2.1.0. 

You can download the latest dev build here (requires being logged in with github account) https://github.com/rizinorg/cutter/actions/runs/2834466024  @superewald Can you try the dev build I linked?

**Comment by superewald** [comment] 2022-08-11 15:43
> Assuming the cause is still the same as before it should be fixed by #2973 . Which was not included in 2.1.0.
> 
> You can download the latest dev build here (requires being logged in with github account) https://github.com/rizinorg/cutter/actions/runs/2834466024 @superewald Can you try the dev build I linked?

Alright, yep that build does list strings correctly :) I just assumed what is included in 2.0.5 should also be in 2.1.0 ^^

**Comment by karliss** [comment] 2022-08-11 17:15
> I just assumed what is included in 2.0.5 should also be in 2.1.0 ^^

I didn't mean that it was somehow removed from 2.1.0 but included 2.0.5. What I wanted to say that the fix was done after 2.1.0 so not included in last official release and definitely not included 2.0.5 which was made before that.

**Closed** 2022-08-11 17:41 UTC
