### ISSUE TITLE
A dos window will be displayed when starting on the new version(>=2.0)

### ISSUE THREAD

**Issue by fenginsc** [rizinorg/cutter#2695] opened 2021-05-25 13:02 UTC
**Environment information**
* Operating System:windows7 x64
* Cutter version:2.0.2
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:
no
**Describe the bug**
The earlier version (1.10) will not have a black framed window (dos window), but a black window will appear when the new version starts.

**To Reproduce**

no

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xarkes** [comment] 2021-05-29 09:22
Hello, thanks for the report.
I think this is a duplicate of https://github.com/rizinorg/cutter/issues/2657, thus I'm closing this issue.

**Closed by xarkes** 2021-05-29 09:22 UTC
