### ISSUE TITLE
1.12.0 release is not hermetic

### ISSUE THREAD

**Issue by rryan** [rizinorg/cutter#2547] opened 2021-01-03 17:57 UTC
**Environment information**
* Operating System: macOS 10.15.7
* Cutter version: 1.12.0
* Obtained from:
  - [] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

Cutter fails to launch:

```
/Applications/Cutter.app/Contents/MacOS/Cutter
Cutter Launch Script for macOS 🥞
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Applications/Cutter.app/Contents/Frameworks/Python.framework/Versions/3.6/Python
  Reason: image not found
/Applications/Cutter.app/Contents/MacOS/Cutter: line 8: 69116 Abort trap: 6           "$EXECDIR/Cutter.bin" "$@"
```

Looking at the included Python framework, it includes paths that seem specific to the build environment:
```
otool -L /Applications/Cutter.app/Contents/Frameworks/Python.framework/Versions/3.6/Python
/Applications/Cutter.app/Contents/Frameworks/Python.framework/Versions/3.6/Python:
	/Users/travis/build/radareorg/cutter-deps/python/Python.framework/Versions/3.6/Python (compatibility version 3.6.0, current version 3.6.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1454.90.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

**Comment by rryan** [comment] 2021-01-03 18:01
/usr/local/opt/gettext/ does not exist on my system.

Thanks for this great software!

**Comment by rryan** [comment] 2021-01-03 18:04
If it's relevant, I installed this with Homebrew (but I think that just downloads `https://github.com/radareorg/cutter/releases/download/v1.12.0/Cutter-v1.12.0-x64.macOS.dmg`).

**Comment by karliss** [comment] 2021-01-03 19:26
Before opening an issue please search the issue tracker for existing issues first. Duplicate of  #2428

**Comment by karliss** [comment] 2021-01-03 19:46
@rryan You can try downloading latest dev build from here https://github.com/rizinorg/cutter/actions/runs/457996120 . It should include all the libs but I was only able to test in macOS 11 . Let us know if it works.

**Comment by rryan** [comment] 2021-01-03 20:14
🤦 sorry about that.

**Comment by xarkes** [comment] 2021-02-13 07:50
Closing as it is a duplicate and fixed.

**Closed by xarkes** 2021-02-13 07:50 UTC
Labels: Build System, macOS
