### ISSUE TITLE
Can't reopen project for ARM cortex with -b 16

### ISSUE THREAD

**Issue by lamashnikov** [rizinorg/cutter#3390] opened 2024-11-12 00:15 UTC
**Environment information**
* Operating System: manjaro 
* Cutter version: 2.3.4-makepkg-209c26b
* Obtained from:
  - [ ] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [x] Distribution repository
* File format: any
 * Arch: N/A
 * Type: data

**Describe the bug**

I've created a project with a flash dump of an embedded device, i manually set up everything when openning the bin file (arch, -b 16, beginning offset of the file in memory ,etc...), did somes anotations on my project. When i was done i saved it and reloaded it later. When reloaded it, all the instruction where invalid 

**To Reproduce**

Open a thumb ARM/ cortex binary file, and configure manually with 16bits (won't work overwise) 
Save the rizin project 
Open it again 

**Expected behavior**
To get the binary loaded with the information i set up at the beginning 

EXPECTED: 

fcn.000008ec(int16_t arg1, int16_t arg2, int32_t arg3);
; arg int16_t arg1 @ r0
; arg int16_t arg2 @ r1
; arg int32_t arg3 @ r2
0x000008ec      push    {r4, r5, r6, r7, lr}
0x000008ee      mov     lr, sb
0x000008f0      mov     r7, r8
0x000008f2      lsls    r5, r2, 0x10 ; arg3
0x000008f4      lsrs    r5, r5, 0x10
0x000008f6      movs    r6, r5
[...]

GOT: 

entry_point(int32_t arg_344h);
; arg int32_t arg_344h @ stack + 0x344
0x100002cc      invalid
0x100002d0      invalid
0x100002d2      invalid
0x100002d4      invalid
0x100002d6      invalid
0x100002da      invalid
0x100002de      invalid
0x100002e2      invalid
0x100002e6      invalid
0x100002ea      invalid
0x100002ee      invalid
0x100002f2      invalid
0x100002f4      invalid
0x100002f6      invalid
0x100002fa      invalid
0x100002fc      invalid
0x100002fe      invalid
0x10000302      invalid
0x10000306      invalid
[...]

**Comment by karliss** [comment] 2024-11-12 08:59
Restoring custom memory mapping (even basic ones) is known missing feature in current rizin projects.

As a workaround (while the feature isn't finished) it should be possible write  a small rzshell script which restores the proper memory mapping and run it after loading the project.  That way all the manual annotations and anaalysis information should be preserved.

Duplicate of #2541

**Closed as not planned by karliss** 2024-11-12 08:59 UTC
Labels: Projects
