### ISSUE TITLE
Hotkeys are not disabled when cursor is in text field

### ISSUE THREAD

**Issue by Rot127** [rizinorg/cutter#3391] opened 2024-11-20 20:04 UTC
**Environment information**
* Operating System: Fedora 40
* Cutter version: 2.3.4
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: ...

**Describe the bug**

If the cursor is in a text field (e.g. in the `Console` to type Rizin commands) the hotkeys are not disabled. This means letters like `s` or `g` can not be typed. Because pressing them performs the hotkey action (for `s`: select the symbol search).

**To Reproduce**

1. Start Cutter
2. Click into the symbol search (`Type flag name or address here`)
3. Type letter `s`
4. Letter is not written

**Expected behavior**

hotkeys can be typed in text fields.

**Screenshots**

**Additional context**

**Comment by karliss** [comment] 2024-11-20 21:39
Duplicate of #3388

Only affects the QT5 appimage build. Works fine in the qt6 appimage build.

**Closed as not planned by karliss** 2024-11-20 21:39 UTC
Labels: BUG, Linux, High Priority, Qt
